package com.hospitalmanagement.enums;

public enum PatientStatus {
    REGISTERED,
    WAITING_FOR_NURSE_ASSESSMENT,
    READY_FOR_DOCTOR_CONSULTATION,
    WAITING_FOR_LABORATORY,
    LABORATORY_RESULTS_AVAILABLE,
    WAITING_FOR_PHARMACY,
    READY_FOR_BILLING,
    COMPLETED,
    ACTIVE,
    ADMITTED,
    OUTPATIENT,
    DISCHARGED,
    INACTIVE
}
